#################MENU##############
GET http://localhost:1500/api/menu

###
POST http://localhost:1500/api/add-item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDUyNDMxOCwiZXhwIjoxNjgwNTYwMzE4fQ.Vk0TT3xEs5KH-MlN7rC2SXIDfn80UBe1CdC2jmCa0QU
Content-Type: application/json

{
    "item_name": "Nuoc dua",
    "description": "Nuoc dua thom ngon",
    "price": 12.99,
    "is_available": true,
    "category": "drink"
}
###
GET http://localhost:1500/api/view-item/838x45um
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDcwOTU5NSwiZXhwIjoxNjgwNzQ1NTk1fQ.titMRFF8STMC4F6F5baDBpJDTGQI8ykhRcgux7-XIJ8
##################ORDER##############

GET http://localhost:1500/api/view-order/5

###
GET http://localhost:1500/api/orders

###
GET http://localhost:1500/api/view-current-orders

###
POST http://localhost:1500/api/add-items/3
Content-Type: application/json

[
    {
        "Name": "Caesar2 Salad",
        "Quantity": 4,
        "Price": 10.99
    },
    {
        "Name": "Nuoc dua",
        "Quantity": 1,
        "Price": 12.99
    }
]

###
POST http://localhost:1500/api/finish-order/3

#################TABLE###############
POST http://localhost:1500/api/assign-table/2/ab

###

POST http://localhost:1500/api/assign-table/2/bc

###
POST http://localhost:1500/api/change-status/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDYyODAyMiwiZXhwIjoxNjgwNjY0MDIyfQ.p4OB_emLm_MelShGY5iItJKE4E1uaNCALfYZ8ZZNObQ
###
GET http://localhost:1500/api/table/1qAKpsUL

###
POST http://localhost:1500/api/request-table/5WLK1rFw

###
POST http://localhost:1500/api/request-checkout/11

###
GET http://localhost:1500/api/table/2
###
GET http://localhost:1500/api/tables
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDU4MDcwOSwiZXhwIjoxNjgwNjE2NzA5fQ.mQ_iLQzb8fj38F3sCYMe6n9KS6z_8rn5fCGsxyTFOkQ
###############PAYMENT##############
GET http://localhost:1500/api/view-payment/1

###
GET http://localhost:1500/api/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDQ0MDQ3MCwiZXhwIjoxNjgwNDc2NDcwfQ.iWlZ9tzZTjgffx-RL9fnSvHPuBp0ii7RzgszRjQGNuQ
###
POST http://localhost:1500/api/request-payment/18

###
POST http://localhost:1500/api/finish-payment/2

#################AUTHENTICATION###############
POST http://localhost:1500/api/login
Content-Type: application/json

{
	"username": "admin",
	"password": "password"
}
###
POST http://localhost:1500/api/logout
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDQ0MzYwNX0.U4k4qJwuNXPiUXc_VlTXERHEkVf2M4a6VMrmvcW4qhg"
}
###
POST http://localhost:1500/api/get-access-token
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYUFiQmNDZEQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTY4MDQ0MDc1N30.NuzLmPCsy3KmXKi7zBmSjvLG05Fx1Ov4Hfra4_Zgi3g"
}