GET http://localhost:1500/api/menu

################################

GET http://localhost:1500/api/view-order/2

################################
GET http://localhost:1500/api/orders

################################
GET http://localhost:1500/api/view-current-orders

################################
POST http://localhost:1500/api/finish-order/3

################################
POST http://localhost:1500/api/assign-table/1/ab

################################

GET http://localhost:1500/api/assign-table/2/bc

################################
POST http://localhost:1500/api/change-status/1

################################
GET http://localhost:1500/api/table/1qAKpsUL

################################
GET http://localhost:1500/api/table/2
################################
GET http://localhost:1500/api/tables